Default filename parameter for save file dialog
tryphotino/photino.NET pull request #213
Opened 2024-09-23 00:46 UTC by Andersen27

Default filename parameter for save file dialog.
This is a solution for issue #140.
Supplied together with PR for Photino.Native.

2024-10-10 16:32 UTC, philippjbauer commented
This looks good all in all. I just added a small change request to the PR. If you can resolve that we will merge it for the next release.

2024-10-10 17:48 UTC, Andersen27 commented
Can't found that change. Anyway i turned on "Allow edits by maintainers" option for my branch.

2024-10-10 18:03 UTC, philippjbauer requested changes

2024-10-10 18:04 UTC, philippjbauer commented
> Can't found that change. Anyway i turned on "Allow edits by maintainers" option for my branch.

Sorry about that. I forgot to submit the review

2025-08-28 15:27 UTC, MikeYeager commented
This will be in the next release.

2025-08-28 15:27 UTC, closed without merging